name: Fetch UBB News

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Start the python script
        run: python main.py
