name: Fetch UBB News

on:
  # deleted cron jobs as AWS lambda will take care
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 redis

      - name: Start the python script
        env:
          NOTIFIER_TAG_NAME: ${{ secrets.NOTIFIER_TAG_NAME }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: python main.py
